### ISSUE TITLE
Odometer 0

### ISSUE THREAD

**Issue by chris2172** [Hyundai-Kia-Connect/hyundai_kia_connect_api#196]
* Hyundai / Kia Connect version:
* Python version:
* Operating System:

### Description

On the dashboard the odometer is showing 0
it looks like a timeout is setting it to 0 after a set period of time.

![image](https://user-images.githubusercontent.com/11930805/208293788-912d22c5-d136-4cf0-8b4c-77eb77fe268a.png)

### What I Did

```
Noticed it over the last few days and I have updated all versions when available
```

**Comment by chris2172** [comment]
Actually look like an issue with the Bluelink app and the car as it is also showing 0 in the bluelink app
Image from Bluelink App
![image](https://user-images.githubusercontent.com/11930805/208294478-70195c1a-c7b6-490f-b752-88d401d8c878.png)

**Comment by chris2172** [comment]
Emailed the Bluelink team asking them why my vehicle is showing 0 Miles in the app.

**Comment by cdnninja** [comment]
It came from the December head unit update.  If the car is off it reports 0.  

What version are you on.  We tried writing logic to ignore the 0 updates.

**Comment by ZuinigeRijder** [comment]
I have contacted Hyundai Europe Bluelink about this problem:

```

To: bluelink@hyundai-europe.com
Subject: Annoying Bluelink odometer bug after installing update 221129 for IONIQ 5

I'm having an annoying Bluelink odometer problem after installing update 
NE_E.EUR.S5W_L.001.001.221129 on December 6th for IONIQ5: 
https://update.hyundai.com/EU/E1/updateNoticeView/623/pop2

I use the latest Bluelink App on Android, 2.0.7, but I think this problem is NOT related to the Bluelink App, 
but because of the infotainment update on my IONIQ 5: NE_E.EUR.S5W_L.001.001.221129

After turning on the car, the odometer is fetched once properly using the Bluelink App, 
after that it fetches an old value, in my case 20795.4 km, while the current value is 20826 km.
Odometer value 20795.4 km was (coincidentally?) the odometer value just before the update installation.

How can I reproduce it?
- Turn on the car and wait for everything to start, including loading the map
- Make sure the Bluelink app is completely closed
- Start the Bluelink App and go to: Status -> Vehicle Report
- The odometer in the Bluelink app shows the correct value.
- Turn off the car and wait 15 minutes.
- Make sure the Bluelink app is completely closed
- Start the Bluelink App and go to: Status -> Vehicle Report
- The odometer in the Bluelink app shows the wrong odometer

Note: I am not forcing data updates with the Bluelink app

My suspicion is that the IONIQ 5 is sending the wrong old odometer to the Bluelink server when it's turned off.
[Others confirmed the same problem:](https://www.goingelectric.de/forum/viewtopic.php?p=1990763#p1990763)

- Yes, the new update is bullshit, see my graphic from my smart home. 
   Since installation, the correct status is only transmitted when driving, then the status during the update... Really great...


However, since the Bluelink app can display the correct odometer when the car is on 
and the data is always transmitted via the Bluelink server, 
this can certainly be solved on the Bluelink server side and does not require a new update in the vehicle.

Can this be solved on the Bluelink Server soon and in future Car Infotainment updates?

Thanks,
```

And they replied:

```
Dear Mr. ZuinigeRijder,

Thank you for your reply.
We would like to inform you that the issue is currently under investigation 
and will be solved as soon as possible.

We deeply apologize for the inconvenience and appreciate your understanding.
```

**Comment by ZuinigeRijder** [comment]
Solving this issue in hyundai_kia_connect_api is not really possible, especially when you only run the program once and then exit. Otherwise you should keep the program running and fetch updates.  My program [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor) is a one shot program, fetch requesting cached Bluelink Server values, writes the values to a file and exits.

I made a poor man's workaround, in the other programs of hyundai_kia_connect_monitor, like summary.py, I keep track of the highest odometer value and ignore lower values. 

But there is also a more serious problem with that, because you have to fetch the latest odometer value when the car is ON. And that means, short trips inside the fetch interval, the correct odometer value at that time is easily missed. And because there is a limit of the number of API calls (in Europe about 200 calls). But I have seen that calling hyundai_kia_connect_api once per 15 minutes (96 calls per day) already reaches the limit in Europe around the evening. Note that a force refresh does also NOT get the latest odometer. 

So this is something Hyundai (and probably Kia) has to fix in the Bluelink Server and/or infotainment update. But then the Bluelink server needs to remember the highest odometer value, when the car sends a push message with the odometer value. Otherwise the infotainment of the car has to be updated with the fix that the latest odometer is send.

**Comment by chris2172** [comment]
I updated the the latest infotainment system just recently.
I did email the bluelink team and got the response below

Thank you for contacting us.
 
We regret to inform you that the issue regarding the odometer reading in the Bluelink app is known, and our team is doing their utmost best to find a fix to it, which is expected with the next software update.
 
We apologize for the inconvenience and appreciate your understanding.

감사합니다 | Best regards | Mit freundlichen Grüßen  
Your Bluelink Team,
Fred

**Comment by zulufoxtrot** [comment]
Same issue on my Kia after upgrading to the latest head unit firmware. The Kia Connect app also reports 0.
Also documented here (French): https://forums.automobile-propre.com/topic/suivi-des-versions-du-gpsautoradio-27951/?do=findComment&comment=1275879
Not much to do but wait for a fix from the manufacturers.

**Comment by ZuinigeRijder** [comment]
This issue is solved on my IONIQ 5 with[ the latest infotainment update 221223](https://update.hyundai.com/EU/E1/updateNoticeView/623/pop2). This odometer problem occurred with version 221129. Also others report this is solved in Kia e-Niro en Kona. So probably this issue can be closed.
